/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#a17c6b',
        'on-primary': '#ffffff',
        'primary-container': '#F6EDE8',
        'on-primary-container': '#4A3328',
        'primary-fixed': '#F6EDE8',
        'primary-fixed-dim': '#EAD6CC',
        'on-primary-fixed': '#2E1F18',
        'on-primary-fixed-variant': '#5C4236',
        'inverse-primary': '#E8C4B4',

        secondary: '#C5A059',
        'on-secondary': '#2E2410',
        'secondary-container': '#F8F1E2',
        'on-secondary-container': '#4E3D1A',
        'secondary-fixed': '#F8F1E2',
        'secondary-fixed-dim': '#EBDDBF',
        'on-secondary-fixed': '#2E2410',
        'on-secondary-fixed-variant': '#5C4A20',

        tertiary: '#6B5344',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#EFE6DF',
        'on-tertiary-container': '#2A1F19',
        'tertiary-fixed': '#EFE6DF',
        'tertiary-fixed-dim': '#D2C2B4',
        'on-tertiary-fixed': '#2A1F19',
        'on-tertiary-fixed-variant': '#6B5344',

        error: '#B3261E',
        'on-error': '#ffffff',
        'error-container': '#F9DEDC',
        'on-error-container': '#410E0B',

        surface: '#FCFAF7',
        'on-surface': '#26201B',
        'surface-dim': '#EDE6DF',
        'surface-bright': '#FCFAF7',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F8F4EF',
        'surface-container': '#F3EEE8',
        'surface-container-high': '#ECE5DD',
        'surface-container-highest': '#E5DCD2',
        'surface-variant': '#E5DCD2',
        'on-surface-variant': '#8A7A6D',

        'inverse-surface': '#33291F',
        'inverse-on-surface': '#F7F0E9',

        outline: '#9A8A7D',
        'outline-variant': '#DDD2C7',
        'surface-tint': '#a17c6b',

        background: '#FCFAF7',
        'on-background': '#26201B',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        'label-bold': ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'body-md': ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'body-lg': ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'display-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'display-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
      },
      fontSize: {
        'label-bold': ['14px', { lineHeight: '1.0', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      boxShadow: {
        'ambient-surface': '0px 4px 20px rgba(60, 40, 30, 0.06)',
        'ambient-primary': '0 10px 25px -5px rgba(161, 124, 107, 0.30)',
        'level-2': '0px 8px 30px rgba(60, 40, 30, 0.10)',
      },
    },
  },
  plugins: [],
};
