/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#a43c12',
        'on-primary': '#ffffff',
        'primary-container': '#ff7f50',
        'on-primary-container': '#6c2000',
        'primary-fixed': '#ffdbcf',
        'primary-fixed-dim': '#ffb59c',
        'on-primary-fixed': '#380c00',
        'on-primary-fixed-variant': '#822800',
        'inverse-primary': '#ffb59c',

        secondary: '#006a62',
        'on-secondary': '#ffffff',
        'secondary-container': '#5ef6e6',
        'on-secondary-container': '#006f66',
        'secondary-fixed': '#61f9e9',
        'secondary-fixed-dim': '#3adccc',
        'on-secondary-fixed': '#00201d',
        'on-secondary-fixed-variant': '#005049',

        tertiary: '#705d00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c0a200',
        'on-tertiary-container': '#453900',
        'tertiary-fixed': '#ffe16d',
        'tertiary-fixed-dim': '#e9c400',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#544600',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        surface: '#fbf9f5',
        'on-surface': '#1b1c1a',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'surface-variant': '#e4e2de',
        'on-surface-variant': '#57423b',

        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f0ed',

        outline: '#8b7169',
        'outline-variant': '#dec0b6',
        'surface-tint': '#a43c12',

        background: '#fbf9f5',
        'on-background': '#1b1c1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'label-bold': ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'display-lg': ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'label-bold': ['14px', { lineHeight: '1.0', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      boxShadow: {
        'ambient-surface': '0px 4px 20px rgba(164, 60, 18, 0.05)',
        'ambient-primary': '0 10px 25px -5px rgba(255, 127, 80, 0.4)',
        'level-2': '0px 8px 30px rgba(164, 60, 18, 0.10)',
      },
    },
  },
  plugins: [],
};
