/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#B2541C',
        'on-primary': '#ffffff',
        'primary-container': '#FBEDE2',
        'on-primary-container': '#4A2C1D',
        'primary-fixed': '#FBEDE2',
        'primary-fixed-dim': '#F3D9C7',
        'on-primary-fixed': '#3A2317',
        'on-primary-fixed-variant': '#6B4128',
        'inverse-primary': '#E8B08A',

        secondary: '#C89B58',
        'on-secondary': '#1A1207',
        'secondary-container': '#F8EEDC',
        'on-secondary-container': '#4A380F',
        'secondary-fixed': '#F8EEDC',
        'secondary-fixed-dim': '#E7D3AC',
        'on-secondary-fixed': '#2A1F08',
        'on-secondary-fixed-variant': '#5C4A20',

        'gold-deep': '#A87A38',
        'on-gold-deep': '#ffffff',

        tertiary: '#4A2C1D',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#F0E6DB',
        'on-tertiary-container': '#2E1B12',
        'tertiary-fixed': '#F0E6DB',
        'tertiary-fixed-dim': '#D3BFA9',
        'on-tertiary-fixed': '#2E1B12',
        'on-tertiary-fixed-variant': '#4A2C1D',

        error: '#B3261E',
        'on-error': '#ffffff',
        'error-container': '#F9DEDC',
        'on-error-container': '#410E0B',

        surface: '#FDFAF6',
        'on-surface': '#2E2016',
        'surface-dim': '#EDE3D6',
        'surface-bright': '#FDFAF6',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F9F4ED',
        'surface-container': '#F4EDE2',
        'surface-container-high': '#EEE4D6',
        'surface-container-highest': '#E7DACA',
        'surface-variant': '#E7DACA',
        'on-surface-variant': '#7A6650',

        'inverse-surface': '#2E2016',
        'inverse-on-surface': '#F9F4ED',

        outline: '#A08B72',
        'outline-variant': '#DDD0BE',
        'surface-tint': '#B2541C',

        background: '#FDFAF6',
        'on-background': '#2E2016',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        'label-bold': ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'body-md': ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'body-lg': ['Poppins', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'display-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'display-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
      },
      fontSize: {
        'label-bold': ['14px', { lineHeight: '1.0', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      boxShadow: {
        'ambient-surface': '0px 4px 20px rgba(74, 44, 29, 0.06)',
        'ambient-primary': '0 10px 25px -5px rgba(178, 84, 28, 0.30)',
        'level-2': '0px 8px 30px rgba(74, 44, 29, 0.10)',
      },
    },
  },
  plugins: [],
};
