const dotenv = require('dotenv');
const mongoose = require('mongoose');

dotenv.config();
const connectDB = require('../config/db');
const Product = require('../models/Product');
const { User } = require('../models/User');
const Order = require('../models/Order');
const Banner = require('../models/Banner');
const Category = require('../models/Category');
const Navigation = require('../models/Navigation');
const Promotion = require('../models/Promotion');
const Settings = require('../models/Settings');

const products = [
  // ═══════════════════════════════════════════════════════════════
  // ELECTRONICS (15)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Vibe Wireless Headphones', slug: 'vibe-wireless-headphones', category: 'Electronics', description: 'Sleek wireless headphones with active noise cancelling and 30hr battery life. Rich, immersive sound for music lovers.', price: 89.99, originalPrice: 129.99, countInStock: 25, rating: 4.5, numReviews: 128, badge: '-30%', isFlashDeal: true, isFeatured: true, isBestseller: true, images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600'], colors: ['#ff7f50', '#006a62', '#1b1c1a'], features: ['Wireless', 'Noise cancelling', '30hr battery'] },
  { name: 'SnapJoy Instant Camera', slug: 'snapjoy-instant-camera', category: 'Electronics', description: 'Compact instant camera with built-in printer. Capture and print moments instantly.', price: 59.0, originalPrice: 69.0, countInStock: 18, rating: 4.0, numReviews: 84, badge: '-15%', isFlashDeal: true, images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600'], colors: ['#40E0D0', '#006a62', '#ffffff'], features: ['Instant print', 'HD lens', 'Vintage filter'] },
  { name: 'Aura Smart Watch', slug: 'aura-smart-watch', category: 'Electronics', description: 'Minimalist smart watch with heart rate, GPS, and 10-day battery. Track your health in style.', price: 119.0, originalPrice: 199.0, countInStock: 30, rating: 4.8, numReviews: 210, badge: '-40%', isFlashDeal: true, isFeatured: true, isBestseller: true, images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600'], colors: ['#e9c400', '#ff7f50', '#006a62'], features: ['Heart rate', 'GPS', '10-day battery'] },
  { name: 'NovaSound Headphones', slug: 'novasound-headphones', category: 'Electronics', description: 'Premium over-ear headphones with Hi-Fi sound and active noise cancelling. Studio-quality audio.', price: 249.99, countInStock: 12, rating: 4.7, numReviews: 156, badge: 'New', isNewArrival: true, isFeatured: true, images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600'], colors: ['#1b1c1a', '#ff7f50', '#fbf9f5'], features: ['Active noise cancelling', 'Hi-Fi sound', '40hr battery'] },
  { name: 'GlowTab Tablet Pro', slug: 'glowtab-tablet-pro', category: 'Electronics', description: 'Ultra-thin tablet with stunning display. Perfect for work and entertainment on the go.', price: 499.0, countInStock: 8, rating: 5.0, numReviews: 84, isFeatured: true, images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600'], colors: ['#006a62', '#1b1c1a', '#ffffff'], features: ['10.9" display', '128GB storage', 'All-day battery'] },
  { name: 'PixelWatch Series 3', slug: 'pixelwatch-series-3', category: 'Electronics', description: 'Vibrant smartwatch with fitness tracking, calls, and water resistance.', price: 199.0, originalPrice: 249.0, countInStock: 15, rating: 4.2, numReviews: 42, badge: 'Sale', images: ['https://images.unsplash.com/photo-1544117519-31c9f4e4f9c1?w=600'], colors: ['#ff7f50', '#1b1c1a', '#40E0D0'], features: ['Fitness tracking', 'Calls', 'Water resistant'] },
  { name: 'BassDrop Bluetooth Speaker', slug: 'bassdrop-bluetooth-speaker', category: 'Electronics', description: 'Portable Bluetooth speaker with 360-degree sound. Waterproof with 20hr battery.', price: 69.99, originalPrice: 89.99, countInStock: 35, rating: 4.6, numReviews: 203, badge: '-22%', isBestseller: true, images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600'], colors: ['#1b1c1a', '#ff7f50', '#40E0D0'], features: ['360° sound', 'IPX7 waterproof', '20hr playtime'] },
  { name: 'LunaRing Smart Ring', slug: 'lunaring-smart-ring', category: 'Electronics', description: 'Titanium smart ring tracking sleep, heart rate, and activity. Invisible tech.', price: 299.0, countInStock: 10, rating: 4.4, numReviews: 67, badge: 'New', isNewArrival: true, images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600'], colors: ['#C0C0C0', '#e9c400', '#1b1c1a'], features: ['Sleep tracking', 'Heart rate', '7-day battery'] },
  { name: 'SparkDock Wireless Charger', slug: 'sparkdock-wireless-charger', category: 'Electronics', description: 'Qi-compatible wireless charger with LED ambient light. Fast charge capable.', price: 29.99, countInStock: 50, rating: 4.3, numReviews: 178, images: ['https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600'], colors: ['#ffffff', '#1b1c1a', '#006a62'], features: ['Qi compatible', 'Fast charge', 'LED indicator'] },
  { name: 'DriftAction Camera 4K', slug: 'driftaction-camera-4k', category: 'Electronics', description: 'Compact 4K action camera with image stabilization. Waterproof to 30m.', price: 179.99, originalPrice: 229.99, countInStock: 20, rating: 4.5, numReviews: 95, badge: '-22%', images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600'], colors: ['#1b1c1a', '#ff7f50'], features: ['4K video', 'Waterproof 30m', 'Voice control'] },
  { name: 'ZenithLaptop Stand', slug: 'zenith-laptop-stand', category: 'Electronics', description: 'Ergonomic aluminum laptop stand with adjustable height. Improves posture.', price: 44.99, countInStock: 40, rating: 4.7, numReviews: 132, isBestseller: true, images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600'], colors: ['#C0C0C0', '#1b1c1a'], features: ['Aluminum', 'Adjustable height', 'Heat dissipation'] },
  { name: 'EchoWave Earbuds Pro', slug: 'echowave-earbuds-pro', category: 'Electronics', description: 'True wireless earbuds with ANC and transparency mode. Crystal-clear calls.', price: 149.99, originalPrice: 199.99, countInStock: 22, rating: 4.8, numReviews: 287, badge: '-25%', isBestseller: true, isFeatured: true, images: ['https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=600'], colors: ['#1b1c1a', '#ffffff', '#ff7f50'], features: ['ANC', 'Transparency mode', '30hr total battery'] },
  { name: 'NovaBook Air 14"', slug: 'novabook-air-14', category: 'Electronics', description: 'Ultra-thin laptop with stunning display, all-day battery, and whisper-quiet design.', price: 999.0, countInStock: 5, rating: 4.9, numReviews: 56, badge: 'Premium', isFeatured: true, images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600'], colors: ['#C0C0C0', '#1b1c1a'], features: ['14" Retina', '16GB RAM', 'All-day battery'] },
  { name: 'OrbitMini Projector', slug: 'orbitmini-projector', category: 'Electronics', description: 'Pocket-sized LED projector with 1080p support. Projects up to 120" screen.', price: 89.99, countInStock: 15, rating: 4.1, numReviews: 43, isNewArrival: true, images: ['https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600'], colors: ['#ffffff', '#1b1c1a'], features: ['1080p', '120" screen', 'Built-in speakers'] },
  { name: 'VortexGaming Mouse', slug: 'vortex-gaming-mouse', category: 'Electronics', description: 'Precision gaming mouse with 16000 DPI sensor and RGB lighting.', price: 59.99, countInStock: 30, rating: 4.6, numReviews: 198, isBestseller: true, images: ['https://images.unsplash.com/photo-1527814050087-3793815479db?w=600'], colors: ['#1b1c1a', '#ff7f50', '#006a62'], features: ['16000 DPI', 'RGB lighting', '8 programmable buttons'] },

  // ═══════════════════════════════════════════════════════════════
  // SMARTPHONES (5)
  // ═══════════════════════════════════════════════════════════════
  { name: 'NovaPhone 15 Pro', slug: 'novaphone-15-pro', category: 'Electronics', description: 'Flagship smartphone with titanium frame, 200MP camera, and all-day battery.', price: 999.99, countInStock: 15, rating: 4.9, numReviews: 340, badge: 'Premium', isFeatured: true, images: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600'], colors: ['#1b1c1a', '#C0C0C0', '#40E0D0'], features: ['200MP camera', 'Titanium frame', '5G'] },
  { name: 'PixelBuds A-Series', slug: 'pixelbuds-a-series', category: 'Electronics', description: 'Affordable true wireless earbuds with great sound and comfortable fit.', price: 49.99, originalPrice: 69.99, countInStock: 45, rating: 4.3, numReviews: 210, badge: '-29%', images: ['https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=600'], colors: ['#1b1c1a', '#ffffff', '#ff7f50'], features: ['True wireless', 'IPX4 water resistant', '8hr battery'] },
  { name: 'UltraCharge Power Bank 20K', slug: 'ultracharge-power-bank', category: 'Electronics', description: '20000mAh power bank with 65W fast charging. Charge 3 devices simultaneously.', price: 39.99, countInStock: 55, rating: 4.5, numReviews: 165, images: ['https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600'], colors: ['#1b1c1a', '#006a62'], features: ['20000mAh', '65W fast charge', '3 USB ports'] },
  { name: 'SlimCase MagSafe Cover', slug: 'slimcase-magsafe', category: 'Electronics', description: 'Ultra-thin MagSafe compatible phone case with wireless charging support.', price: 24.99, countInStock: 80, rating: 4.2, numReviews: 95, images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600'], colors: ['#1b1c1a', '#ffffff', '#ff7f50', '#006a62'], features: ['MagSafe compatible', 'Slim profile', 'Military grade'] },
  { name: 'ScreenShield Tempered Glass', slug: 'screenshield-tempered-glass', category: 'Electronics', description: 'Premium tempered glass screen protector with oleophobic coating.', price: 12.99, countInStock: 100, rating: 4.1, numReviews: 320, images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600'], colors: ['#ffffff'], features: ['9H hardness', 'Oleophobic', 'Easy install'] },

  // ═══════════════════════════════════════════════════════════════
  // FASHION — Men's (8)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Midnight Leather Jacket', slug: 'midnight-leather-jacket', category: 'Fashion', description: 'Premium faux leather jacket with modern slim fit. Timeless style, vegan-friendly.', price: 189.99, originalPrice: 249.99, countInStock: 12, rating: 4.8, numReviews: 76, badge: '-24%', isFeatured: true, images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600'], colors: ['#1b1c1a', '#8B4513'], features: ['Faux leather', 'Slim fit', 'Vegan-friendly'] },
  { name: 'Denim Classic Jacket', slug: 'denim-classic-jacket', category: 'Fashion', description: 'Timeless denim jacket with relaxed fit. Pre-washed for softness.', price: 84.99, originalPrice: 109.99, countInStock: 30, rating: 4.5, numReviews: 145, badge: '-23%', isBestseller: true, images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600'], colors: ['#4169E1', '#1b1c1a'], features: ['100% cotton', 'Relaxed fit', 'Pre-washed'] },
  { name: 'Classic Leather Belt', slug: 'classic-leather-belt', category: 'Fashion', description: 'Genuine leather belt with brushed nickel buckle. Reversible design.', price: 39.99, countInStock: 30, rating: 4.6, numReviews: 124, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'], colors: ['#1b1c1a', '#8B4513'], features: ['Genuine leather', 'Nickel buckle', 'Reversible'] },
  { name: 'Urban Polo Shirt', slug: 'urban-polo-shirt', category: 'Fashion', description: 'Classic cotton polo shirt with modern slim fit. Breathable pique fabric.', price: 34.99, countInStock: 45, rating: 4.4, numReviews: 89, images: ['https://images.unsplash.com/photo-1625910513413-5fc42dec9db4?w=600'], colors: ['#1b1c1a', '#006a62', '#ff7f50', '#ffffff'], features: ['Cotton pique', 'Slim fit', 'Ribbed collar'] },
  { name: 'Tech Chino Pants', slug: 'tech-chino-pants', category: 'Fashion', description: 'Stretch chino pants with water-repellent finish. Comfortable for all-day wear.', price: 54.99, countInStock: 35, rating: 4.5, numReviews: 72, images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600'], colors: ['#1b1c1a', '#C0C0C0', '#8B4513'], features: ['Stretch fabric', 'Water repellent', 'Slim fit'] },
  { name: 'Sport Sunglasses UV400', slug: 'sport-sunglasses-uv400', category: 'Fashion', description: 'Polarized sports sunglasses with UV400 protection. Anti-fog lens.', price: 29.99, countInStock: 60, rating: 4.4, numReviews: 178, images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600'], colors: ['#1b1c1a', '#ff7f50', '#C0C0C0'], features: ['UV400', 'Polarized', 'Anti-fog'] },
  { name: 'Wool Blend Beanie', slug: 'wool-blend-beanie', category: 'Fashion', description: 'Cozy knit beanie with fleece lining. Warm and stylish for cold weather.', price: 19.99, countInStock: 45, rating: 4.5, numReviews: 98, images: ['https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600'], colors: ['#1b1c1a', '#ff7f50', '#40E0D0', '#e9c400'], features: ['Wool blend', 'Fleece lined', 'Unisex'] },
  { name: 'Performance Running Shorts', slug: 'performance-running-shorts', category: 'Fashion', description: 'Lightweight running shorts with built-in liner and zip pocket.', price: 29.99, countInStock: 50, rating: 4.3, numReviews: 112, images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600'], colors: ['#1b1c1a', '#006a62', '#ff7f50'], features: ['Lightweight', 'Zip pocket', 'Built-in liner'] },

  // ═══════════════════════════════════════════════════════════════
  // FASHION — Women's (8)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Boho Maxi Dress', slug: 'boho-maxi-dress', category: 'Fashion', description: 'Flowy bohemian maxi dress with vibrant floral print. Perfect for summer.', price: 64.99, countInStock: 25, rating: 4.4, numReviews: 56, images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600'], colors: ['#ff7f50', '#40E0D0', '#e9c400'], features: ['Floral print', 'Flowy fit', 'Machine washable'] },
  { name: 'Silk Blend Scarf', slug: 'silk-blend-scarf', category: 'Fashion', description: 'Luxurious silk blend scarf with abstract art print. Lightweight and chic.', price: 34.99, countInStock: 40, rating: 4.3, numReviews: 67, isNewArrival: true, images: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600'], colors: ['#ff7f50', '#006a62', '#e9c400'], features: ['Silk blend', 'Art print', 'Hand-finished edges'] },
  { name: 'Performance Yoga Pants', slug: 'performance-yoga-pants', category: 'Fashion', description: 'High-waist yoga pants with 4-way stretch. Moisture-wicking fabric.', price: 54.99, countInStock: 35, rating: 4.8, numReviews: 312, badge: 'Bestseller', isBestseller: true, isFeatured: true, images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600'], colors: ['#1b1c1a', '#006a62', '#ff7f50'], features: ['4-way stretch', 'Moisture-wicking', 'High-waist'] },
  { name: 'Sunny Crossbody Bag', slug: 'sunny-crossbody-bag', category: 'Fashion', description: 'Vibrant crossbody bag with adjustable strap. Compact and stylish.', price: 39.99, originalPrice: 55.0, countInStock: 22, rating: 4.1, numReviews: 67, badge: '-27%', isFeatured: true, images: ['https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600'], colors: ['#40E0D0', '#006a62', '#ff7f50'], features: ['Adjustable strap', 'Water-resistant', 'Multiple pockets'] },
  { name: 'Floral Wrap Top', slug: 'floral-wrap-top', category: 'Fashion', description: 'Flattering wrap top with floral print. V-neckline and tie waist.', price: 28.99, countInStock: 30, rating: 4.5, numReviews: 45, isNewArrival: true, images: ['https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600'], colors: ['#ff7f50', '#40E0D0', '#e9c400'], features: ['Wrap style', 'Floral print', 'Tie waist'] },
  { name: 'Linen Wide Leg Pants', slug: 'linen-wide-leg-pants', category: 'Fashion', description: 'Relaxed linen-blend wide leg pants. Breezy and comfortable for summer.', price: 42.99, countInStock: 28, rating: 4.4, numReviews: 38, images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600'], colors: ['#fbf9f5', '#006a62', '#1b1c1a'], features: ['Linen blend', 'Wide leg', 'Elastic waist'] },
  { name: 'Canvas Tote Bag', slug: 'canvas-tote-bag', category: 'Fashion', description: 'Durable organic cotton canvas tote. Roomy, eco-friendly, everyday ready.', price: 24.99, countInStock: 55, rating: 4.2, numReviews: 210, isBestseller: true, images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600'], colors: ['#ffffff', '#1b1c1a', '#ff7f50'], features: ['Organic cotton', 'Inner pockets', 'Reinforced handles'] },
  { name: 'Ribbed Knit Cardigan', slug: 'ribbed-knit-cardigan', category: 'Fashion', description: 'Cozy ribbed cardigan with button closure. Perfect layering piece.', price: 49.99, countInStock: 20, rating: 4.6, numReviews: 52, images: ['https://images.unsplash.com/photo-1434389677669-e08b4cda3a19?w=600'], colors: ['#fbf9f5', '#ff7f50', '#1b1c1a'], features: ['Ribbed knit', 'Button closure', 'Oversized fit'] },

  // ═══════════════════════════════════════════════════════════════
  // FASHION — Shoes (5)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Coral Comfort Sneakers', slug: 'coral-comfort-sneakers', category: 'Fashion', description: 'Lightweight, breathable sneakers with memory foam. All-day comfort.', price: 74.99, countInStock: 60, rating: 4.5, numReviews: 190, isBestseller: true, images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600'], colors: ['#ff7f50', '#ffffff', '#1b1c1a'], features: ['Memory foam', 'Breathable', 'Rubber sole'] },
  { name: 'CloudWalk Running Shoes', slug: 'cloudwalk-running-shoes', category: 'Fashion', description: 'Ultra-lightweight running shoes with responsive cushioning.', price: 109.99, countInStock: 45, rating: 4.7, numReviews: 234, isBestseller: true, isFeatured: true, images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600'], colors: ['#ff7f50', '#006a62', '#1b1c1a'], features: ['Ultra-light', 'Responsive cushion', 'Breathable mesh'] },
  { name: 'Leather Chelsea Boots', slug: 'leather-chelsea-boots', category: 'Fashion', description: 'Classic Chelsea boots in premium leather. Elastic side panels for easy on/off.', price: 129.99, countInStock: 18, rating: 4.6, numReviews: 89, images: ['https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600'], colors: ['#1b1c1a', '#8B4513'], features: ['Genuine leather', 'Elastic sides', 'Pull tab'] },
  { name: 'Canvas Slip-Ons', slug: 'canvas-slip-ons', category: 'Fashion', description: 'Classic canvas slip-on shoes. Effortless style for everyday wear.', price: 34.99, countInStock: 50, rating: 4.3, numReviews: 156, images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600'], colors: ['#ffffff', '#1b1c1a', '#006a62'], features: ['Canvas upper', 'Slip-on style', 'Flex sole'] },
  { name: 'Platform Sandals', slug: 'platform-sandals', category: 'Fashion', description: 'Trendy platform sandals with adjustable straps. Elevated summer style.', price: 59.99, countInStock: 25, rating: 4.4, numReviews: 67, isNewArrival: true, images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600'], colors: ['#1b1c1a', '#ff7f50', '#C0C0C0'], features: ['Platform sole', 'Adjustable straps', 'Cushioned footbed'] },

  // ═══════════════════════════════════════════════════════════════
  // HOME DECOR — Kitchen (5)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Terra Ceramic Mug', slug: 'terra-ceramic-mug', category: 'Home Decor', description: 'Minimalist ceramic coffee mug in terracotta. Microwave safe, 12oz.', price: 24.0, countInStock: 50, rating: 4.6, numReviews: 210, isBestseller: true, images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600'], colors: ['#a43c12', '#ff7f50', '#ffffff'], features: ['Handmade', 'Microwave safe', '12oz capacity'] },
  { name: 'Joyful Ceramic Mug Set', slug: 'joyful-ceramic-mug-set', category: 'Home Decor', description: 'Set of 2 bright ceramic mugs. Dishwasher safe, holds warmth.', price: 24.0, countInStock: 40, rating: 4.8, numReviews: 300, isBestseller: true, images: ['https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=600'], colors: ['#e9c400', '#ff7f50', '#a43c12'], features: ['Set of 2', 'Dishwasher safe', 'Holds warmth'] },
  { name: 'Chef\'s Knife Premium', slug: 'chefs-knife-premium', category: 'Home Decor', description: 'German steel chef\'s knife with ergonomic handle. Razor-sharp blade.', price: 49.99, originalPrice: 69.99, countInStock: 20, rating: 4.9, numReviews: 89, badge: '-29%', images: ['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600'], colors: ['#1b1c1a', '#C0C0C0'], features: ['German steel', 'Ergonomic handle', 'Razor sharp'] },
  { name: 'Bamboo Cutting Board Set', slug: 'bamboo-cutting-board-set', category: 'Home Decor', description: 'Set of 3 bamboo cutting boards with juice grooves. Sustainable material.', price: 32.0, countInStock: 35, rating: 4.5, numReviews: 124, images: ['https://images.unsplash.com/photo-1594226801341-41427b4e5c22?w=600'], colors: ['#D2B48C'], features: ['Bamboo', 'Set of 3', 'Juice grooves'] },
  { name: 'Non-Stick Pan Set', slug: 'non-stick-pan-set', category: 'Home Decor', description: 'Set of 3 non-stick pans with tempered glass lids. PFOA-free coating.', price: 59.99, originalPrice: 79.99, countInStock: 18, rating: 4.6, numReviews: 156, badge: '-25%', images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600'], colors: ['#1b1c1a', '#C0C0C0'], features: ['Non-stick', 'PFOA-free', 'Glass lids'] },

  // ═══════════════════════════════════════════════════════════════
  // HOME DECOR — Living Room & Bedroom (8)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Cozy Knit Blanket', slug: 'cozy-knit-blanket', category: 'Home Decor', description: 'Cozy knitted blanket that conveys warmth and comfort. Machine washable.', price: 45.0, countInStock: 20, rating: 4.4, numReviews: 96, isFeatured: true, images: ['https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600'], colors: ['#5ef6e6', '#ffb59c', '#fbf9f5'], features: ['Soft knit', 'Machine washable', '50" x 60"'] },
  { name: 'Linen Throw Pillows', slug: 'linen-throw-pillows', category: 'Home Decor', description: 'Set of 2 soft linen throw pillows with hidden zipper. Neutral tones.', price: 38.0, countInStock: 28, rating: 4.6, numReviews: 92, images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600'], colors: ['#fbf9f5', '#C0C0C0', '#ffb59c'], features: ['Linen', 'Hidden zipper', 'Set of 2'] },
  { name: 'Aromatic Soy Candle Set', slug: 'aromatic-soy-candle-set', category: 'Home Decor', description: 'Hand-poured soy candles in ceramic vessels. 3 scents, 40hr burn time.', price: 32.0, countInStock: 35, rating: 4.7, numReviews: 168, badge: 'Popular', isFeatured: true, images: ['https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600'], colors: ['#fbf9f5', '#ffb59c', '#006a62'], features: ['Soy wax', '3 scents', '40hr burn time'] },
  { name: 'Geometric Wall Mirror', slug: 'geometric-wall-mirror', category: 'Home Decor', description: 'Stunning hexagonal wall mirror with brass frame. Adds depth and light.', price: 89.99, countInStock: 12, rating: 4.5, numReviews: 45, badge: 'New', isNewArrival: true, images: ['https://images.unsplash.com/photo-1618220179428-22790b461013?w=600'], colors: ['#e9c400', '#C0C0C0'], features: ['Hexagonal', 'Brass frame', 'Wall mount'] },
  { name: 'Ceramic Vase Trio', slug: 'ceramic-vase-trio', category: 'Home Decor', description: 'Set of 3 handcrafted ceramic vases. Perfect for fresh or dried flowers.', price: 56.0, countInStock: 15, rating: 4.8, numReviews: 38, badge: 'New', isNewArrival: true, images: ['https://images.unsplash.com/photo-1612198188708-27b3ab0e3c59?w=600'], colors: ['#fbf9f5', '#006a62', '#ff7f50'], features: ['Set of 3', 'Handcrafted', 'Drainage holes'] },
  { name: 'Scented Reed Diffuser', slug: 'scented-reed-diffuser', category: 'Home Decor', description: 'Luxury reed diffuser with essential oil blend. Lasts up to 3 months.', price: 22.0, countInStock: 40, rating: 4.5, numReviews: 115, images: ['https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600'], colors: ['#fbf9f5', '#006a62'], features: ['Essential oils', '3 month fragrance', '8 reeds'] },
  { name: 'Handwoven Jute Rug', slug: 'handwoven-jute-rug', category: 'Home Decor', description: 'Natural jute area rug with handwoven texture. Eco-friendly, 5x7 ft.', price: 79.99, countInStock: 10, rating: 4.3, numReviews: 52, images: ['https://images.unsplash.com/photo-1600166898405-da9535204843?w=600'], colors: ['#D2B48C'], features: ['Natural jute', 'Handwoven', '5x7 ft'] },
  { name: 'Marble & Gold Bookends', slug: 'marble-gold-bookends', category: 'Home Decor', description: 'Elegant marble bookends with gold-finish brackets. Weighted base.', price: 42.0, countInStock: 18, rating: 4.7, numReviews: 34, isNewArrival: true, images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600'], colors: ['#ffffff', '#e9c400'], features: ['Genuine marble', 'Gold finish', 'Weighted base'] },

  // ═══════════════════════════════════════════════════════════════
  // TOYS (10)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Snuggle Plush Bear', slug: 'snuggle-plush-bear', category: 'Toys', description: 'Soft, huggable plush bear. Extra soft, machine washable, 20 inches.', price: 29.99, countInStock: 45, rating: 4.9, numReviews: 320, isBestseller: true, isFeatured: true, images: ['https://images.unsplash.com/photo-1559454403-b8a6b6b7b6c5?w=600'], colors: ['#ffb59c', '#fbf9f5', '#e9c400'], features: ['Extra soft', 'Machine washable', '20 inches'] },
  { name: 'Build-A-Joy Blocks', slug: 'build-a-joy-blocks', category: 'Toys', description: '100 colorful building blocks. Non-toxic, educational, sparks creativity.', price: 34.99, countInStock: 35, rating: 4.7, numReviews: 140, images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600'], colors: ['#ff7f50', '#40E0D0', '#e9c400'], features: ['100 pieces', 'Non-toxic', 'Educational'] },
  { name: 'Galaxy Puzzle 1000pc', slug: 'galaxy-puzzle-1000pc', category: 'Toys', description: '1000-piece jigsaw puzzle with stunning nebula photograph. Premium finish.', price: 19.99, countInStock: 30, rating: 4.6, numReviews: 87, images: ['https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=600'], colors: ['#1b1c1a', '#40E0D0', '#ff7f50'], features: ['1000 pieces', 'Matte finish', '27x20"'] },
  { name: 'STEM Robot Kit', slug: 'stem-robot-kit', category: 'Toys', description: 'Build-your-own robot kit with 200+ parts. Learn coding and engineering.', price: 49.99, countInStock: 20, rating: 4.8, numReviews: 56, badge: 'Popular', images: ['https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=600'], colors: ['#ff7f50', '#006a62'], features: ['200+ parts', 'Coding included', 'Ages 8+'] },
  { name: 'Wooden Train Set Deluxe', slug: 'wooden-train-set-deluxe', category: 'Toys', description: 'Premium wooden train set with 80 pieces. Non-toxic paint, universal fit.', price: 59.99, countInStock: 15, rating: 4.9, numReviews: 198, badge: 'Bestseller', isBestseller: true, images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600'], colors: ['#ff7f50', '#006a62', '#e9c400'], features: ['80 pieces', 'Non-toxic', 'Universal fit'] },
  { name: 'Art Supply Box 150pc', slug: 'art-supply-box-150pc', category: 'Toys', description: 'Complete art kit with 150 pieces: crayons, markers, pencils, watercolors.', price: 39.99, countInStock: 25, rating: 4.7, numReviews: 134, images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600'], colors: ['#ff7f50', '#40E0D0', '#e9c400', '#1b1c1a'], features: ['150 pieces', 'All-in-one', 'Ages 4+'] },
  { name: 'Dinosaur Action Figures 12pc', slug: 'dinosaur-action-figures', category: 'Toys', description: '12 realistic dinosaur figures with facts booklet. Hand-painted, durable.', price: 27.99, countInStock: 40, rating: 4.8, numReviews: 267, isBestseller: true, images: ['https://images.unsplash.com/photo-1519669556878-63bdad8a1a49?w=600'], colors: ['#2E8B57', '#8B4513', '#ff7f50'], features: ['12 figures', 'Hand-painted', 'Fact booklet'] },
  { name: 'Magnetic Tiles 120pc', slug: 'magnetic-tiles-120pc', category: 'Toys', description: 'Colorful magnetic building tiles. STEM learning, strong magnets.', price: 44.99, countInStock: 30, rating: 4.9, numReviews: 189, badge: 'Top Rated', isFeatured: true, images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600'], colors: ['#ff7f50', '#40E0D0', '#e9c400', '#006a62'], features: ['120 pieces', 'Strong magnets', 'STEM certified'] },
  { name: 'Remote Control Race Car', slug: 'remote-control-race-car', category: 'Toys', description: 'High-speed RC race car with rechargeable battery. 2.4GHz, 30 min playtime.', price: 34.99, countInStock: 22, rating: 4.5, numReviews: 112, images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600'], colors: ['#ff7f50', '#1b1c1a', '#006a62'], features: ['2.4GHz', 'Rechargeable', '30 min playtime'] },
  { name: 'Deluxe Play Kitchen Set', slug: 'deluxe-play-kitchen-set', category: 'Toys', description: 'Realistic play kitchen with lights, sounds, and 20 accessories.', price: 89.99, originalPrice: 119.99, countInStock: 8, rating: 4.8, numReviews: 76, badge: '-25%', images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=600'], colors: ['#fbf9f5', '#ff7f50'], features: ['Lights & sounds', '20 accessories', 'Easy assembly'] },

  // ═══════════════════════════════════════════════════════════════
  // BEAUTY & PERSONAL CARE (10)
  // ═══════════════════════════════════════════════════════════════
  { name: 'HydraGlow Serum', slug: 'hydraglow-serum', category: 'Beauty', description: 'Vitamin C brightening serum with hyaluronic acid. Reduces dark spots.', price: 34.99, countInStock: 40, rating: 4.7, numReviews: 234, badge: 'Popular', isBestseller: true, images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'], colors: ['#fbf9f5'], features: ['Vitamin C', 'Hyaluronic acid', 'Dark spot reduction'] },
  { name: 'Rose Petal Moisturizer', slug: 'rose-petal-moisturizer', category: 'Beauty', description: 'Lightweight moisturizer with rose extract. Hydrates without greasiness.', price: 28.99, countInStock: 35, rating: 4.5, numReviews: 178, images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'], colors: ['#ffb59c', '#fbf9f5'], features: ['Rose extract', 'Lightweight', 'Non-greasy'] },
  { name: 'Mineral Sunscreen SPF 50', slug: 'mineral-sunscreen-spf50', category: 'Beauty', description: 'Broad spectrum mineral sunscreen. Reef-safe, lightweight, no white cast.', price: 22.99, countInStock: 50, rating: 4.6, numReviews: 145, images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'], colors: ['#ffffff', '#e9c400'], features: ['SPF 50', 'Reef-safe', 'No white cast'] },
  { name: 'Charcoal Detox Mask', slug: 'charcoal-detox-mask', category: 'Beauty', description: 'Deep cleansing charcoal mask. Unclogs pores, removes impurities.', price: 18.99, countInStock: 45, rating: 4.4, numReviews: 112, images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'], colors: ['#1b1c1a'], features: ['Activated charcoal', 'Deep cleanse', 'Pore minimizing'] },
  { name: 'Silk Pillowcase Set', slug: 'silk-pillowcase-set', category: 'Beauty', description: 'Pure mulberry silk pillowcase set. Reduces hair frizz and skin creases.', price: 39.99, originalPrice: 54.99, countInStock: 25, rating: 4.8, numReviews: 189, badge: '-27%', isFeatured: true, images: ['https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=600'], colors: ['#fbf9f5', '#ffb59c', '#006a62'], features: ['100% mulberry silk', 'Set of 2', 'Hypoallergenic'] },
  { name: 'Bamboo Hair Brush Set', slug: 'bamboo-hair-brush-set', category: 'Beauty', description: 'Set of 3 bamboo hair brushes. Detangles, reduces static, eco-friendly.', price: 24.99, countInStock: 30, rating: 4.5, numReviews: 89, images: ['https://images.unsplash.com/photo-1522338242992-e1a54571a7f8?w=600'], colors: ['#D2B48C'], features: ['Bamboo', 'Set of 3', 'Anti-static'] },
  { name: 'Hydrating Lip Balm 3-Pack', slug: 'hydrating-lip-balm-3pack', category: 'Beauty', description: 'Natural lip balm with shea butter and coconut oil. 3 delicious flavors.', price: 12.99, countInStock: 60, rating: 4.6, numReviews: 267, images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'], colors: ['#ffb59c', '#ff7f50', '#e9c400'], features: ['Shea butter', 'Coconut oil', '3 flavors'] },
  { name: 'Volumizing Shampoo Bar', slug: 'volumizing-shampoo-bar', category: 'Beauty', description: 'Plastic-free shampoo bar with natural ingredients. Lasts 80+ washes.', price: 14.99, countInStock: 40, rating: 4.4, numReviews: 156, images: ['https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600'], colors: ['#fbf9f5', '#006a62'], features: ['Plastic-free', 'Natural ingredients', '80+ washes'] },
  { name: 'Retinol Night Cream', slug: 'retinol-night-cream', category: 'Beauty', description: 'Anti-aging night cream with retinol and peptides. Reduces fine lines.', price: 44.99, countInStock: 20, rating: 4.7, numReviews: 134, isNewArrival: true, images: ['https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=600'], colors: ['#fbf9f5', '#ff7f50'], features: ['Retinol', 'Peptides', 'Anti-aging'] },
  { name: 'Professional Makeup Brush Set', slug: 'professional-makeup-brush-set', category: 'Beauty', description: '12-piece professional makeup brush set with travel case. Synthetic bristles.', price: 29.99, countInStock: 35, rating: 4.5, numReviews: 198, images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'], colors: ['#1b1c1a', '#ff7f50', '#C0C0C0'], features: ['12 pieces', 'Synthetic bristles', 'Travel case'] },

  // ═══════════════════════════════════════════════════════════════
  // SPORTS & FITNESS (10)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Yoga Mat Premium', slug: 'yoga-mat-premium', category: 'Sports', description: 'Extra thick yoga mat with alignment lines. Non-slip, eco-friendly TPE.', price: 39.99, countInStock: 30, rating: 4.7, numReviews: 234, isBestseller: true, images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600'], colors: ['#006a62', '#ff7f50', '#1b1c1a', '#40E0D0'], features: ['Extra thick', 'Alignment lines', 'Non-slip'] },
  { name: 'Resistance Bands Set', slug: 'resistance-bands-set', category: 'Sports', description: 'Set of 5 resistance bands with different strengths. Portable workout kit.', price: 24.99, countInStock: 50, rating: 4.5, numReviews: 189, images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600'], colors: ['#ff7f50', '#e9c400', '#006a62', '#1b1c1a', '#C0C0C0'], features: ['5 levels', 'Portable', 'Carry bag included'] },
  { name: 'Stainless Steel Water Bottle', slug: 'stainless-steel-water-bottle', category: 'Sports', description: 'Double-wall vacuum insulated bottle. Keeps cold 24hr, hot 12hr.', price: 22.99, countInStock: 60, rating: 4.6, numReviews: 312, images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600'], colors: ['#1b1c1a', '#C0C0C0', '#006a62', '#ff7f50'], features: ['Double-wall', 'BPA free', '750ml capacity'] },
  { name: 'Jump Rope Speed Pro', slug: 'jump-rope-speed-pro', category: 'Sports', description: 'Adjustable speed jump rope with ball bearings. Anti-tangle cable.', price: 16.99, countInStock: 40, rating: 4.4, numReviews: 145, images: ['https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=600'], colors: ['#1b1c1a', '#ff7f50', '#006a62'], features: ['Adjustable', 'Ball bearings', 'Anti-tangle'] },
  { name: 'Foam Roller Recovery', slug: 'foam-roller-recovery', category: 'Sports', description: 'High-density foam roller for muscle recovery. Textured surface.', price: 29.99, countInStock: 25, rating: 4.5, numReviews: 167, images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600'], colors: ['#006a62', '#ff7f50', '#1b1c1a'], features: ['High density', 'Textured surface', '18 inch'] },
  { name: 'Gym Duffle Bag', slug: 'gym-duffle-bag', category: 'Sports', description: 'Water-resistant gym duffle with shoe compartment. 40L capacity.', price: 34.99, countInStock: 30, rating: 4.4, numReviews: 123, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'], colors: ['#1b1c1a', '#006a62', '#C0C0C0'], features: ['Water-resistant', 'Shoe compartment', '40L capacity'] },
  { name: 'Boxing Gloves Pro', slug: 'boxing-gloves-pro', category: 'Sports', description: 'Premium leather boxing gloves with gel padding. Breathable lining.', price: 49.99, countInStock: 15, rating: 4.6, numReviews: 89, images: ['https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=600'], colors: ['#ff7f50', '#1b1c1a', '#ba1a1a'], features: ['Gel padding', 'Breathable', '12oz / 14oz'] },
  { name: 'Swim Goggles Anti-Fog', slug: 'swim-goggles-anti-fog', category: 'Sports', description: 'Anti-fog swim goggles with UV protection. Adjustable silicone strap.', price: 18.99, countInStock: 45, rating: 4.3, numReviews: 178, images: ['https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=600'], colors: ['#006a62', '#1b1c1a', '#40E0D0'], features: ['Anti-fog', 'UV protection', 'Silicone strap'] },
  { name: 'Cycling Gloves Padded', slug: 'cycling-gloves-padded', category: 'Sports', description: 'Gel-padded cycling gloves with touch screen compatible fingertips.', price: 19.99, countInStock: 35, rating: 4.4, numReviews: 112, images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600'], colors: ['#1b1c1a', '#ff7f50', '#006a62'], features: ['Gel padded', 'Touch screen', 'Breathable'] },
  { name: 'Tennis Racket Carbon', slug: 'tennis-racket-carbon', category: 'Sports', description: 'Lightweight carbon fiber tennis racket. Oversized head, vibration dampening.', price: 89.99, originalPrice: 119.99, countInStock: 10, rating: 4.7, numReviews: 56, badge: '-25%', images: ['https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=600'], colors: ['#1b1c1a', '#006a62', '#ff7f50'], features: ['Carbon fiber', 'Oversized head', 'Vibration dampening'] },

  // ═══════════════════════════════════════════════════════════════
  // BOOKS & STATIONERY (8)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Flow Notebook', slug: 'flow-notebook', category: 'Books', description: 'Stylish soft-cover notebook with dotted grid. Lay-flat binding, 120 pages.', price: 18.0, countInStock: 100, rating: 4.3, numReviews: 150, images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600'], colors: ['#40E0D0', '#a43c12', '#ffffff'], features: ['120 pages', 'Dotted grid', 'Lay-flat binding'] },
  { name: 'Premium Pen Set', slug: 'premium-pen-set', category: 'Books', description: 'Set of 3 premium gel pens with ergonomic grip. Smooth writing.', price: 14.99, countInStock: 80, rating: 4.5, numReviews: 134, images: ['https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600'], colors: ['#1b1c1a', '#006a62', '#ff7f50'], features: ['Gel ink', 'Ergonomic grip', 'Set of 3'] },
  { name: 'Desktop Planner 2026', slug: 'desktop-planner-2026', category: 'Books', description: 'Undated weekly/monthly planner with habit tracker. Premium paper.', price: 22.99, countInStock: 45, rating: 4.6, numReviews: 89, isNewArrival: true, images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600'], colors: ['#1b1c1a', '#ff7f50', '#006a62'], features: ['Undated', 'Habit tracker', 'Premium paper'] },
  { name: 'Colored Pencil Set 72pc', slug: 'colored-pencil-set-72pc', category: 'Books', description: 'Professional colored pencils with soft wax core. Vivid, blendable colors.', price: 29.99, countInStock: 25, rating: 4.7, numReviews: 167, images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600'], colors: ['#ff7f50', '#40E0D0', '#e9c400'], features: ['72 colors', 'Soft wax core', 'Blendable'] },
  { name: 'Creative Writing Journal', slug: 'creative-writing-journal', category: 'Books', description: 'Leather-bound journal with lined pages. Ribbon bookmark, 200 pages.', price: 16.99, countInStock: 35, rating: 4.4, numReviews: 78, images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600'], colors: ['#8B4513', '#1b1c1a', '#fbf9f5'], features: ['Leather bound', '200 pages', 'Ribbon bookmark'] },
  { name: 'Washi Tape Collection', slug: 'washi-tape-collection', category: 'Books', description: 'Set of 12 decorative washi tapes. Perfect for journaling and crafts.', price: 12.99, countInStock: 55, rating: 4.5, numReviews: 210, images: ['https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600'], colors: ['#ff7f50', '#40E0D0', '#e9c400', '#ffb59c'], features: ['12 rolls', '15mm width', 'Multiple patterns'] },
  { name: 'Sketch Pad A4', slug: 'sketch-pad-a4', category: 'Books', description: 'Heavyweight sketch pad with acid-free paper. 80 sheets, spiral bound.', price: 14.99, countInStock: 40, rating: 4.3, numReviews: 112, images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600'], colors: ['#ffffff', '#1b1c1a'], features: ['A4 size', '80 sheets', 'Acid-free'] },
  { name: 'Bookmark Set Metal', slug: 'bookmark-set-metal', category: 'Books', description: 'Set of 4 elegant metal bookmarks. Magnetic closure, gift box included.', price: 9.99, countInStock: 60, rating: 4.2, numReviews: 156, images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=600'], colors: ['#C0C0C0', '#e9c400'], features: ['Metal', 'Magnetic', 'Gift box'] },

  // ═══════════════════════════════════════════════════════════════
  // PET SUPPLIES (8)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Cozy Pet Bed', slug: 'cozy-pet-bed', category: 'Pet Supplies', description: 'Soft plush pet bed with memory foam. Removable washable cover.', price: 34.99, countInStock: 25, rating: 4.7, numReviews: 189, isBestseller: true, images: ['https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=600'], colors: ['#fbf9f5', '#ffb59c', '#C0C0C0'], features: ['Memory foam', 'Washable cover', 'Anti-slip base'] },
  { name: 'Interactive Cat Toy', slug: 'interactive-cat-toy', category: 'Pet Supplies', description: 'Electronic interactive cat toy with rotating feathers. USB rechargeable.', price: 19.99, countInStock: 40, rating: 4.5, numReviews: 145, images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600'], colors: ['#ff7f50', '#006a62'], features: ['Electronic', 'Rotating feathers', 'USB rechargeable'] },
  { name: 'Stainless Steel Pet Bowls', slug: 'stainless-steel-pet-bowls', category: 'Pet Supplies', description: 'Set of 2 stainless steel bowls with silicone mat. Non-slip, dishwasher safe.', price: 24.99, countInStock: 50, rating: 4.6, numReviews: 234, images: ['https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=600'], colors: ['#C0C0C0', '#ff7f50'], features: ['Stainless steel', 'Silicone mat', 'Dishwasher safe'] },
  { name: 'Dog Leash Retractable', slug: 'dog-leash-retractable', category: 'Pet Supplies', description: 'Retractable dog leash with one-hand brake. 16ft tangle-free cord.', price: 18.99, countInStock: 35, rating: 4.4, numReviews: 167, images: ['https://images.unsplash.com/photo-1601758124277-f00ce7a19e19?w=600'], colors: ['#1b1c1a', '#ff7f50', '#006a62'], features: ['Retractable', '16ft cord', 'One-hand brake'] },
  { name: 'Cat Scratching Post', slug: 'cat-scratching-post', category: 'Pet Supplies', description: 'Multi-level cat tree with sisal posts and perch. Durable construction.', price: 49.99, countInStock: 15, rating: 4.6, numReviews: 123, images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600'], colors: ['#D2B48C', '#fbf9f5'], features: ['Sisal posts', 'Multi-level', 'Perch included'] },
  { name: 'Pet Grooming Kit', slug: 'pet-grooming-kit', category: 'Pet Supplies', description: 'Complete pet grooming kit with 8 tools. Nail clippers, brush, comb.', price: 29.99, countInStock: 30, rating: 4.5, numReviews: 98, images: ['https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600'], colors: ['#C0C0C0', '#ff7f50'], features: ['8 tools', 'Nail clippers', 'Travel case'] },
  { name: 'Dog Treats Organic', slug: 'dog-treats-organic', category: 'Pet Supplies', description: 'Organic peanut butter dog treats. Grain-free, no artificial flavors.', price: 14.99, countInStock: 60, rating: 4.8, numReviews: 267, images: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600'], colors: ['#8B4513', '#e9c400'], features: ['Organic', 'Grain-free', 'No artificial flavors'] },
  { name: 'Cat Litter Box Self-Cleaning', slug: 'cat-litter-box-self-cleaning', category: 'Pet Supplies', description: 'Automatic self-cleaning litter box. Quiet motor, odor control.', price: 149.99, countInStock: 8, rating: 4.4, numReviews: 56, badge: 'Premium', images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600'], colors: ['#C0C0C0', '#1b1c1a'], features: ['Self-cleaning', 'Quiet motor', 'Odor control'] },

  // ═══════════════════════════════════════════════════════════════
  // GROCERY & GOURMET (6)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Artisan Coffee Beans', slug: 'artisan-coffee-beans', category: 'Grocery', description: 'Single-origin Arabica beans, medium roast. Notes of chocolate and citrus.', price: 18.99, countInStock: 45, rating: 4.7, numReviews: 312, isBestseller: true, images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600'], colors: ['#8B4513'], features: ['Arabica', 'Medium roast', 'Single-origin'] },
  { name: 'Organic Matcha Powder', slug: 'organic-matcha-powder', category: 'Grocery', description: 'Ceremonial grade organic matcha. Stone-ground, vibrant green, 30 servings.', price: 24.99, countInStock: 30, rating: 4.6, numReviews: 189, images: ['https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=600'], colors: ['#2E8B57'], features: ['Ceremonial grade', 'Organic', '30 servings'] },
  { name: 'Dark Chocolate Collection', slug: 'dark-chocolate-collection', category: 'Grocery', description: 'Premium dark chocolate assortment. 72% cacao, 12 flavors, gift box.', price: 29.99, originalPrice: 39.99, countInStock: 25, rating: 4.8, numReviews: 156, badge: '-25%', images: ['https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600'], colors: ['#8B4513'], features: ['72% cacao', '12 flavors', 'Gift box'] },
  { name: 'Honey Gift Set', slug: 'honey-gift-set', category: 'Grocery', description: 'Set of 3 raw honey varieties. Wildflower, lavender, and clover.', price: 34.99, countInStock: 20, rating: 4.7, numReviews: 89, images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600'], colors: ['#e9c400', '#8B4513'], features: ['Raw honey', '3 varieties', 'Glass jars'] },
  { name: 'Granola Mix Variety Pack', slug: 'granola-mix-variety', category: 'Grocery', description: '6-pack of artisan granola. Maple pecan, blueberry, coconut, and more.', price: 22.99, countInStock: 35, rating: 4.5, numReviews: 145, images: ['https://images.unsplash.com/photo-1517093602195-b40af9688b41?w=600'], colors: ['#e9c400', '#8B4513', '#2E8B57'], features: ['6 flavors', 'No added sugar', 'Gluten-free options'] },
  { name: 'Olive Oil Extra Virgin', slug: 'olive-oil-extra-virgin', category: 'Grocery', description: 'Cold-pressed extra virgin olive oil from Italy. Rich flavor, 500ml.', price: 16.99, countInStock: 40, rating: 4.6, numReviews: 178, images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600'], colors: ['#2E8B57', '#e9c400'], features: ['Cold-pressed', 'Italian', '500ml'] },

  // ═══════════════════════════════════════════════════════════════
  // AUTOMOTIVE & TOOLS (6)
  // ═══════════════════════════════════════════════════════════════
  { name: 'Car Phone Mount', slug: 'car-phone-mount', category: 'Automotive', description: 'Magnetic car phone mount with dashboard clip. 360° rotation.', price: 19.99, countInStock: 50, rating: 4.5, numReviews: 234, images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600'], colors: ['#1b1c1a', '#C0C0C0'], features: ['Magnetic', '360° rotation', 'Dashboard clip'] },
  { name: 'Car Air Freshener Set', slug: 'car-air-freshener-set', category: 'Automotive', description: 'Set of 4 premium car air fresheners. Long-lasting 60-day fragrance.', price: 12.99, countInStock: 60, rating: 4.3, numReviews: 189, images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600'], colors: ['#ff7f50', '#006a62', '#e9c400', '#ffb59c'], features: ['4 pack', '60-day fragrance', 'Natural oils'] },
  { name: 'LED Car Interior Kit', slug: 'led-car-interior-kit', category: 'Automotive', description: 'RGB LED car interior light kit with music sync. App controlled.', price: 29.99, countInStock: 25, rating: 4.4, numReviews: 156, images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600'], colors: ['#ff7f50', '#006a62', '#40E0D0', '#e9c400'], features: ['RGB LED', 'Music sync', 'App controlled'] },
  { name: 'Portable Tire Inflator', slug: 'portable-tire-inflator', category: 'Automotive', description: 'Digital portable tire inflator. 12V DC, auto shut-off, LED light.', price: 39.99, countInStock: 20, rating: 4.6, numReviews: 123, images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600'], colors: ['#1b1c1a', '#C0C0C0'], features: ['12V DC', 'Auto shut-off', 'LED light'] },
  { name: 'Multi-Tool Pocket Knife', slug: 'multi-tool-pocket-knife', category: 'Automotive', description: '15-in-1 multi-tool with pliers, knife, screwdriver. Stainless steel.', price: 24.99, countInStock: 35, rating: 4.7, numReviews: 189, images: ['https://images.unsplash.com/photo-1504567961542-e24d9439a724?w=600'], colors: ['#C0C0C0', '#1b1c1a'], features: ['15 tools', 'Stainless steel', 'Belt clip'] },
  { name: 'Jump Starter Power Pack', slug: 'jump-starter-power-pack', category: 'Automotive', description: 'Compact car jump starter with USB charging. 2000A peak current.', price: 59.99, originalPrice: 79.99, countInStock: 15, rating: 4.5, numReviews: 89, badge: '-25%', images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600'], colors: ['#1b1c1a', '#ff7f50'], features: ['2000A peak', 'USB charging', 'Compact'] },
];

const banners = [
  { title: 'Summer Sale!', subtitle: 'Up to 50% off', description: 'Shop the biggest sale of the season', image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1200', link: '/shop', ctaText: 'Shop Now', position: 'hero', isActive: true, order: 0, bgColor: '#fff5f0' },
  { title: 'New Arrivals', subtitle: 'Fresh drops weekly', description: 'Check out the latest products', image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200', link: '/shop', ctaText: 'Explore', position: 'hero', isActive: true, order: 1, bgColor: '#f0fffe' },
  { title: 'Free Shipping', subtitle: 'On orders over $50', description: 'Free standard shipping on qualifying orders', image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200', link: '/shop', ctaText: 'Shop Now', position: 'promo', isActive: true, order: 0, bgColor: '#fbf9f5' },
  { title: 'Flash Deal', subtitle: 'Limited time only', description: 'Grab before it\'s gone', image: 'https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=800', link: '/shop?flash=true', ctaText: 'View Deals', position: 'promo', isActive: true, order: 1, bgColor: '#fff0f0' },
  { title: 'New Collection', subtitle: 'Explore the latest', description: 'Be the first to shop new arrivals', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800', link: '/shop', ctaText: 'Shop New', position: 'promo', isActive: true, order: 2, bgColor: '#f0fffe' },
  { title: 'Best Sellers', subtitle: 'Top picks this week', description: 'Discover what everyone loves', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', link: '/shop', ctaText: 'See All', position: 'sidebar', isActive: true, order: 0, bgColor: '#fff5f0' },
  { title: '20% Off First Order', subtitle: 'Use code WELCOME20', description: 'Sign up and save', image: 'https://images.unsplash.com/photo-1556742393-d75f468bfcb0?w=800', link: '/register', ctaText: 'Sign Up', position: 'sidebar', isActive: true, order: 1, bgColor: '#f0fffe' },
  { title: 'Secure Checkout', subtitle: '100% protected payments', description: 'Shop with confidence', image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800', link: '/shop', ctaText: 'Shop Now', position: 'footer', isActive: true, order: 0, bgColor: '#f0fffe' },
  { title: 'Free Returns', subtitle: '30-day return policy', description: 'Not satisfied? Return for free', image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800', link: '/shop', ctaText: 'Learn More', position: 'footer', isActive: true, order: 1, bgColor: '#fbf9f5' },
];

const categories = [
  { name: 'Electronics', slug: 'electronics', description: 'Gadgets, devices, and tech essentials', icon: 'devices', image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=600', isActive: true, order: 0, productCount: 20 },
  { name: 'Fashion', slug: 'fashion', description: 'Trendy clothing, shoes, and accessories', icon: 'apparel', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600', isActive: true, order: 1, productCount: 34 },
  { name: 'Home Decor', slug: 'home-decor', description: 'Beautiful items for your living space', icon: 'deck', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600', isActive: true, order: 2, productCount: 13 },
  { name: 'Toys', slug: 'toys', description: 'Fun and educational toys for all ages', icon: 'toys', image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=600', isActive: true, order: 3, productCount: 10 },
  { name: 'Beauty', slug: 'beauty', description: 'Skincare, haircare, and makeup essentials', icon: 'spa', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600', isActive: true, order: 4, productCount: 10 },
  { name: 'Sports', slug: 'sports', description: 'Fitness gear and outdoor equipment', icon: 'fitness_center', image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600', isActive: true, order: 5, productCount: 10 },
  { name: 'Books', slug: 'books', description: 'Notebooks, stationery, and reading essentials', icon: 'menu_book', image: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600', isActive: true, order: 6, productCount: 8 },
  { name: 'Pet Supplies', slug: 'pet-supplies', description: 'Everything for your furry friends', icon: 'pets', image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600', isActive: true, order: 7, productCount: 8 },
  { name: 'Grocery', slug: 'grocery', description: 'Coffee, snacks, and gourmet treats', icon: 'coffee', image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600', isActive: true, order: 8, productCount: 6 },
  { name: 'Automotive', slug: 'automotive', description: 'Car accessories and tools', icon: 'directions_car', image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600', isActive: true, order: 9, productCount: 6 },
];

const navigationItems = [
  { label: 'Home', url: '/', order: 0, isActive: true, position: 'header' },
  { label: 'Shop', url: '/shop', order: 1, isActive: true, position: 'header' },
  { label: 'Deals', url: '/shop?flash=true', order: 2, isActive: true, position: 'header' },
  { label: 'New Arrivals', url: '/shop?sort=newest=true', order: 3, isActive: true, position: 'header' },
  { label: 'Support', url: '/account', order: 0, isActive: true, position: 'footer' },
  { label: 'Privacy Policy', url: '/privacy', order: 1, isActive: true, position: 'footer' },
  { label: 'Terms of Service', url: '/terms', order: 2, isActive: true, position: 'footer' },
];

const promotions = [
  { name: 'Summer Blowout', code: 'SUMMER50', description: '50% off all orders', type: 'percentage', value: 50, minPurchase: 100, maxDiscount: 75, usageLimit: 500, usedCount: 127, isActive: true, startDate: new Date('2026-06-01'), endDate: new Date('2026-09-01') },
  { name: 'Welcome Discount', code: 'WELCOME10', description: '$10 off first order', type: 'fixed', value: 10, minPurchase: 30, usageLimit: 0, usedCount: 89, isActive: true, startDate: new Date('2026-01-01'), endDate: new Date('2026-12-31') },
  { name: 'Free Shipping Friday', code: 'FRIDAYSHIP', description: 'Free shipping on all orders', type: 'free_shipping', value: 0, minPurchase: 0, usageLimit: 200, usedCount: 45, isActive: true, startDate: new Date('2026-01-01'), endDate: new Date('2026-12-31') },
  { name: 'Welcome Discount', code: 'WELCOME20', description: '20% off for new customers', type: 'percentage', value: 20, minPurchase: 25, maxDiscount: 50, usageLimit: 1000, usedCount: 234, isActive: true, showInSidebar: true, sidebarTitle: 'New Customer?', sidebarSubtitle: 'Get 20% off your first order', sidebarButtonText: 'Shop Now', sidebarBgColor: '#a43c12', startDate: new Date('2026-01-01'), endDate: new Date('2026-12-31') },
];

const seed = async () => {
  try {
    await connectDB();

    console.log('Clearing existing data...');
    await Product.deleteMany({});
    await User.deleteMany({});
    await Order.deleteMany({});
    await Banner.deleteMany({});
    await Category.deleteMany({});
    await Navigation.deleteMany({});
    await Promotion.deleteMany({});
    await Settings.deleteMany({});

    const createdProducts = await Product.insertMany(products);
    console.log(`Seeded ${createdProducts.length} products`);

    const users = [
      { name: 'Jordan Mitchell', email: 'superadmin@novacart.com', password: 'password123', isAdmin: true, role: 'super_admin', phone: '+1 (415) 555-0100', avatar: '', address: { fullName: 'Jordan Mitchell', street: '100 Market Street, Suite 500', city: 'San Francisco', zip: '94105' }, loyaltyPoints: 0, isActive: true },
      { name: 'Sarah Chen', email: 'admin@novacart.com', password: 'password123', isAdmin: true, role: 'admin', phone: '+1 (415) 555-0101', avatar: '', address: { fullName: 'Sarah Chen', street: '250 Brannan Street', city: 'San Francisco', zip: '94107' }, loyaltyPoints: 0, isActive: true },
      { name: 'Marcus Rivera', email: 'content@novacart.com', password: 'password123', isAdmin: true, role: 'content_manager', phone: '+1 (415) 555-0102', avatar: '', address: { fullName: 'Marcus Rivera', street: '88 Colin P Kelly Jr Street', city: 'San Francisco', zip: '94107' }, loyaltyPoints: 0, isActive: true },
      { name: 'Emily Nakamura', email: 'orders@novacart.com', password: 'password123', isAdmin: true, role: 'order_manager', phone: '+1 (415) 555-0103', avatar: '', address: { fullName: 'Emily Nakamura', street: '425 Market Street, Floor 12', city: 'San Francisco', zip: '94105' }, loyaltyPoints: 0, isActive: true },
      { name: 'Alex Johnson', email: 'alex@novacart.com', password: 'password123', role: 'customer', phone: '+1 (555) 234-5678', avatar: '', address: { fullName: 'Alex Johnson', street: '742 Evergreen Terrace', city: 'Springfield', zip: '62704' }, loyaltyPoints: 850, wishlist: [createdProducts[0]._id, createdProducts[6]._id], isActive: true },
      { name: 'Maria Garcia', email: 'maria@novacart.com', password: 'password123', role: 'customer', phone: '+1 (555) 345-6789', avatar: '', address: { fullName: 'Maria Garcia', street: '1600 Pennsylvania Avenue', city: 'Washington', zip: '20500' }, loyaltyPoints: 420, wishlist: [createdProducts[2]._id, createdProducts[12]._id], isActive: true },
      { name: 'David Kim', email: 'david@novacart.com', password: 'password123', role: 'customer', phone: '+1 (555) 456-7890', avatar: '', address: { fullName: 'David Kim', street: '350 Fifth Avenue', city: 'New York', zip: '10118' }, loyaltyPoints: 1200, wishlist: [createdProducts[3]._id], isActive: true },
      { name: 'Priya Patel', email: 'priya@novacart.com', password: 'password123', role: 'customer', phone: '+1 (555) 567-8901', avatar: '', address: { fullName: 'Priya Patel', street: '233 S Wacker Drive', city: 'Chicago', zip: '60606' }, loyaltyPoints: 675, wishlist: [createdProducts[4]._id, createdProducts[9]._id], isActive: true },
    ];

    for (const userData of users) {
      await User.create(userData);
    }
    console.log(`Seeded ${users.length} users`);

    const customerIds = await User.find({ role: 'customer' }).select('_id');
    if (customerIds.length > 0) {
      const sampleOrders = [
        { user: customerIds[0]._id, orderItems: [{ name: createdProducts[0].name, qty: 1, image: createdProducts[0].images[0], price: createdProducts[0].price, product: createdProducts[0]._id }, { name: createdProducts[6].name, qty: 2, image: createdProducts[6].images[0], price: createdProducts[6].price, product: createdProducts[6]._id }], shippingAddress: { fullName: 'Alex Johnson', street: '742 Evergreen Terrace', city: 'Springfield', zip: '62704' }, paymentMethod: 'Card', itemsPrice: 137.99, taxPrice: 11.04, shippingPrice: 0, totalPrice: 149.03, status: 'Delivered', isPaid: true, paidAt: new Date('2026-08-15') },
        { user: customerIds[0]._id, orderItems: [{ name: createdProducts[3].name, qty: 1, image: createdProducts[3].images[0], price: createdProducts[3].price, product: createdProducts[3]._id }], shippingAddress: { fullName: 'Alex Johnson', street: '742 Evergreen Terrace', city: 'Springfield', zip: '62704' }, paymentMethod: 'Card', itemsPrice: 249.99, taxPrice: 20.00, shippingPrice: 0, totalPrice: 269.99, status: 'Shipped', isPaid: true, paidAt: new Date('2026-08-25') },
        { user: customerIds[1]._id, orderItems: [{ name: createdProducts[2].name, qty: 1, image: createdProducts[2].images[0], price: createdProducts[2].price, product: createdProducts[2]._id }, { name: createdProducts[10].name, qty: 1, image: createdProducts[10].images[0], price: createdProducts[10].price, product: createdProducts[10]._id }], shippingAddress: { fullName: 'Maria Garcia', street: '1600 Pennsylvania Avenue', city: 'Washington', zip: '20500' }, paymentMethod: 'Card', itemsPrice: 158.99, taxPrice: 12.72, shippingPrice: 5.99, totalPrice: 177.70, status: 'Processing', isPaid: true, paidAt: new Date('2026-08-28') },
        { user: customerIds[2]._id, orderItems: [{ name: createdProducts[4].name, qty: 1, image: createdProducts[4].images[0], price: createdProducts[4].price, product: createdProducts[4]._id }], shippingAddress: { fullName: 'David Kim', street: '350 Fifth Avenue', city: 'New York', zip: '10118' }, paymentMethod: 'PayPal', itemsPrice: 499.00, taxPrice: 39.92, shippingPrice: 0, totalPrice: 538.92, status: 'Pending', isPaid: false },
        { user: customerIds[3]._id, orderItems: [{ name: createdProducts[8].name, qty: 3, image: createdProducts[8].images[0], price: createdProducts[8].price, product: createdProducts[8]._id }, { name: createdProducts[12].name, qty: 1, image: createdProducts[12].images[0], price: createdProducts[12].price, product: createdProducts[12]._id }], shippingAddress: { fullName: 'Priya Patel', street: '233 S Wacker Drive', city: 'Chicago', zip: '60606' }, paymentMethod: 'Card', itemsPrice: 83.97, taxPrice: 6.72, shippingPrice: 5.99, totalPrice: 96.68, status: 'Delivered', isPaid: true, paidAt: new Date('2026-08-20') },
        { user: customerIds[0]._id, orderItems: [{ name: createdProducts[11].name, qty: 1, image: createdProducts[11].images[0], price: createdProducts[11].price, product: createdProducts[11]._id }], shippingAddress: { fullName: 'Alex Johnson', street: '742 Evergreen Terrace', city: 'Springfield', zip: '62704' }, paymentMethod: 'Card', itemsPrice: 74.99, taxPrice: 6.00, shippingPrice: 5.99, totalPrice: 86.98, status: 'Cancelled', isPaid: false },
      ];
      await Order.insertMany(sampleOrders);
      console.log(`Seeded ${sampleOrders.length} orders`);
    }

    await Banner.insertMany(banners);
    console.log(`Seeded ${banners.length} banners`);

    await Category.insertMany(categories);
    console.log(`Seeded ${categories.length} categories`);

    await Navigation.insertMany(navigationItems);
    console.log(`Seeded ${navigationItems.length} navigation items`);

    await Promotion.insertMany(promotions);
    console.log(`Seeded ${promotions.length} promotions`);

    await Settings.create({});
    console.log('Created default settings');

    console.log('\n--- Seeding Complete ---');
    console.log(`Total: ${products.length} products, ${users.length} users, ${categories.length} categories`);
    console.log('\n--- Demo Accounts ---');
    console.log('Super Admin:    superadmin@novacart.com / password123');
    console.log('Admin:          admin@novacart.com / password123');
    console.log('Content Mgr:    content@novacart.com / password123');
    console.log('Order Mgr:      orders@novacart.com / password123');
    console.log('Customer:       alex@novacart.com / password123');
    console.log('Customer:       maria@novacart.com / password123');
    console.log('Customer:       david@novacart.com / password123');
    console.log('Customer:       priya@novacart.com / password123');

    process.exit(0);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

seed();
